### ISSUE TITLE
[Bug] Sync to Notion failed

### ISSUE THREAD

**Issue by eallion** [lizheming/doumark-action#10]
The database id and notion integrantion token are correct.

https://github.com/eallion/eallion.com/actions/runs/5632390673/job/15260293179

```shell
    - name: Sync Movie to Notion
      uses: lizheming/doumark-action@master
      with:
        id: eallion
        type: movie
        format: notion
        dir: cbbdf33235e64061a7ddb6716217f8a9
        notion_token: ${{ secrets.NOTION_ACCESS_TOKEN }}
```

```log
@notionhq/client warn: request fail {
  code: 'validation_error',
  message: 'body failed validation. Fix one:\n' +
    'body.properties.id.title should be defined, instead was `undefined`.\n' +
    'body.properties.id.rich_text should be defined, instead was `undefined`.\n' +
    'body.properties.id.number should be a number or `null`, instead was `"30433455"`.\n' +
    'body.properties.id.url should be defined, instead was `undefined`.\n' +
    'body.properties.id.select should be defined, instead was `undefined`.\n' +
    'body.properties.id.multi_select should be defined, instead was `undefined`.\n' +
    'body.properties.id.people should be defined, instead was `undefined`.\n' +
    'body.properties.id.email should be defined, instead was `undefined`.\n' +
    'body.properties.id.phone_number should be defined, instead was `undefined`.\n' +
    'body.properties.id.date should be defined, instead was `undefined`.\n' +
    'body.properties.id.checkbox should be defined, instead was `undefined`.\n' +
    'body.properties.id.relation should be defined, instead was `undefined`.\n' +
    'body.properties.id.files should be defined, instead was `undefined`.\n' +
    'body.properties.id.status should be defined, instead was `undefined`.\n' +
    'body.properties.title.id should be defined, instead was `undefined`.\n' +
    'body.properties.title.name should be defined, instead was `undefined`.\n' +
    'body.properties.title.start should be defined, instead was `undefined`.'
}
/snapshot/drone-doumark/node_modules/@notionhq/client/build/src/errors.js:162
        return new APIResponseError({
               ^

APIResponseError: body failed validation. Fix one:
body.properties.id.title should be defined, instead was `undefined`.
body.properties.id.rich_text should be defined, instead was `undefined`.
body.properties.id.number should be a number or `null`, instead was `"30433455"`.
body.properties.id.url should be defined, instead was `undefined`.
body.properties.id.select should be defined, instead was `undefined`.
body.properties.id.multi_select should be defined, instead was `undefined`.
body.properties.id.people should be defined, instead was `undefined`.
body.properties.id.email should be defined, instead was `undefined`.
body.properties.id.phone_number should be defined, instead was `undefined`.
body.properties.id.date should be defined, instead was `undefined`.
body.properties.id.checkbox should be defined, instead was `undefined`.
body.properties.id.relation should be defined, instead was `undefined`.
body.properties.id.files should be defined, instead was `undefined`.
body.properties.id.status should be defined, instead was `undefined`.
body.properties.title.id should be defined, instead was `undefined`.
body.properties.title.name should be defined, instead was `undefined`.
body.properties.title.start should be defined, instead was `undefined`.
    at buildRequestError (/snapshot/drone-doumark/node_modules/@notionhq/client/build/src/errors.js:162:16)
    at Client.request (/snapshot/drone-doumark/node_modules/@notionhq/client/build/src/Client.js:304:54)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async NotionStore.set (/snapshot/drone-doumark/src/store/notion.js)
    at async exec (/snapshot/drone-doumark/src/plugin.js) {
  code: 'validation_error',
  status: 400,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [ 'Sat, 22 Jul 2023 19:36:03 GMT' ],
      'content-type': [ 'application/json; charset=utf-8' ],
      'transfer-encoding': [ 'chunked' ],
      connection: [ 'close' ],
      'x-powered-by': [ 'Express' ],
      etag: [ 'W/"538-B+r9PT+5bLSUBLrM9I+WlZ/Jetc"' ],
      vary: [ 'Accept-Encoding' ],
      'content-encoding': [ 'gzip' ],
      'cf-cache-status': [ 'DYNAMIC' ],
      'set-cookie': [
        '__cf_bm=n5niPrEE00_RYXhuKTmf8S18bBeuDRqryl23v3B4Paw-1690054563-0-ATN28XEhSXy++SK4BEybTjmrCG/2SoI6fl3p3XrsOTFLkXHMjChq0h3nRsAc6jOhvA8ElFBCwaeLXyrUlnPVRqI=; path=/; expires=Sat, 22-Jul-23 20:06:03 GMT; domain=.notion.com; HttpOnly; Secure; SameSite=None'
      ],
      server: [ 'cloudflare' ],
      'cf-ray': [ '7eae2[15](https://github.com/eallion/eallion.com/actions/runs/5632390673/job/15260293179#step:6:16)ebcf50bfb-DFW' ]
    }
  },
  body: '{"object":"error","status":400,"code":"validation_error","message":"body failed validation. Fix one:\\nbody.properties.id.title should be defined, instead was `undefined`.\\nbody.properties.id.rich_text should be defined, instead was `undefined`.\\nbody.properties.id.number should be a number or `null`, instead was `\\"[30](https://github.com/eallion/eallion.com/actions/runs/5632390673/job/15260293179#step:6:31)4[33](https://github.com/eallion/eallion.com/actions/runs/5632390673/job/15260293179#step:6:34)[45](https://github.com/eallion/eallion.com/actions/runs/5632390673/job/15260293179#step:6:46)5\\"`.\\nbody.properties.id.url should be defined, instead was `undefined`.\\nbody.properties.id.select should be defined, instead was `undefined`.\\nbody.properties.id.multi_select should be defined, instead was `undefined`.\\nbody.properties.id.people should be defined, instead was `undefined`.\\nbody.properties.id.email should be defined, instead was `undefined`.\\nbody.properties.id.phone_number should be defined, instead was `undefined`.\\nbody.properties.id.date should be defined, instead was `undefined`.\\nbody.properties.id.checkbox should be defined, instead was `undefined`.\\nbody.properties.id.relation should be defined, instead was `undefined`.\\nbody.properties.id.files should be defined, instead was `undefined`.\\nbody.properties.id.status should be defined, instead was `undefined`.\\nbody.properties.title.id should be defined, instead was `undefined`.\\nbody.properties.title.name should be defined, instead was `undefined`.\\nbody.properties.title.start should be defined, instead was `undefined`."}'
}
```

**Comment by lizheming** [comment]
#8 反馈了 id 不对的问题，后来发现取错字段修复了。不过没注意到这两个 id 的类型是不同的，一个是数字一个是字符串。Notion 基于 JSON Schema 对类型有比较强的校验，这块类型指定有问题就报错了，已修复可以再看看。

**Comment by eallion** [comment]
https://github.com/eallion/eallion.com/actions/runs/5636011218/job/15267626887
好像还是不行。
```
Unexpected input(s) 'neodb_token', valid inputs are ['entryPoint', 'args', 'id', 'type', 'status', 'format', 'dir', 'notion_token']
```
另外就是 NeoDB 显示同步成功了，不过在 NeoDB 那边没有更新。

**Comment by lizheming** [comment]
1. Notion 不行是因为你的数据里有一条空数据，导致后续获取最新的标记时间错误而影响了后续的逻辑。目前已经对空数据做了过滤，也可以直接把空数据删除也能恢复正常。

  ![image](https://github.com/lizheming/doumark-action/assets/424491/a7d4337d-0314-42be-b2e3-459a6fda12b5)

2. NeoDB 的问题是 `action.yml` 里面没有增加 `neodb_token` 的参数，目前已更新，可以再试试

**Comment by eallion** [comment]
还是报错：https://github.com/eallion/eallion.com/actions/runs/5637930371/job/15271538521

**Comment by lizheming** [comment]
重新 Duplicate 下模板，后面 PR 新增了两个属性导出，模板没有加上，现在更新了

**Comment by eallion** [comment]
第一次运行就有点慢，后面就很好了。

不过在豆瓣的新标记，好像没有同步到 NeoDB。
https://movie.douban.com/people/eallion/collect

1917 是新标记的。

https://neodb.social/users/eallion@mastodon.social/complete/movie/

**Comment by lizheming** [comment]
NeoDB 的更新已修复，有个单词拼写错误

**Comment by eallion** [comment]
完美了。感谢！
