### ISSUE TITLE
图书部分同步Notion错误

### ISSUE THREAD

**Issue by Akelio-zhang** [lizheming/doumark-action#11]
```
@notionhq/client warn: request fail {
  code: 'validation_error',
  message: 'body failed validation: body.properties.intro.rich_text[0].text.content.length should be ≤ `2000`, instead was `2242`.'
}
/snapshot/drone-doumark/node_modules/@notionhq/client/build/src/errors.js:162
        return new APIResponseError({
               ^

APIResponseError: body failed validation: body.properties.intro.rich_text[0].text.content.length should be ≤ `2000`, instead was `2242`.
    at buildRequestError (/snapshot/drone-doumark/node_modules/@notionhq/client/build/src/errors.js:162:16)
    at Client.request (/snapshot/drone-doumark/node_modules/@notionhq/client/build/src/Client.js:304:54)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async NotionStore.set (/snapshot/drone-doumark/src/store/notion.js)
    at async exec (/snapshot/drone-doumark/src/plugin.js) {
  code: 'validation_error',
  status: 400,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [ 'Sat, 30 Dec 2023 [13](https://github.com/Akelio-zhang/akelio-zhang/actions/runs/7364191275/job/20044351288#step:4:14):02:55 GMT' ],
      'content-type': [ 'application/json; charset=utf-8' ],
      'content-length': [ '242' ],
      connection: [ 'close' ],
      'x-powered-by': [ 'Express' ],
      'x-notion-request-id': [ '31652855-6f43-4e53-94b3-c02f400956cf' ],
      etag: [ 'W/"f2-ihTvnoHnrKWf6zox98rINr1cmAE"' ],
      vary: [ 'Accept-Encoding' ],
      'cf-cache-status': [ 'DYNAMIC' ],
      'set-cookie': [
        '__cf_bm=1dEjBc55ol7ouQKDKdy3ecJG9NTxf19x6PJvby0D49Y-1703941375-1-AVCo/kcQ2XQWNfEq5Xe0UXDBmqtDrNEukBA1JPzA6VXacv30il2AzHUiAyxHb5n6QyHG6n1IzFtx[15](https://github.com/Akelio-zhang/akelio-zhang/actions/runs/7364191275/job/20044351288#step:4:16)ZWRAYcXjE=; path=/; expires=Sat, 30-Dec-23 13:32:55 GMT; domain=.notion.com; HttpOnly; Secure; SameSite=None'
      ],
      server: [ 'cloudflare' ],
      'cf-ray': [ '83da7adcdd8f0778-IAD' ]
    }
  },
  body: '{"object":"error","status":400,"code":"validation_error","message":"body failed validation: body.properties.intro.rich_text[0].text.content.length should be ≤ `2000`, instead was `2242`.","request_id":"3[16](https://github.com/Akelio-zhang/akelio-zhang/actions/runs/7364191275/job/20044351288#step:4:17)5[28](https://github.com/Akelio-zhang/akelio-zhang/actions/runs/7364191275/job/20044351288#step:4:29)55-6f43-4e53-94b3-c02f[40](https://github.com/Akelio-zhang/akelio-zhang/actions/runs/7364191275/job/20044351288#step:4:41)0956cf"}'
}
```

错误内容如上，感觉是图书的intro字段太长，notion api报错。

**Comment by lizheming** [comment]
close with lizheming/drone-doumark#5
